package com.sonuverma.deeploader.data.models

/**
 * Represents the result of extracting media info from a URL.
 * Contains all available streams, metadata, and thumbnails.
 */
data class ExtractionResult(
    val id: String,
    val title: String,
    val description: String = "",
    val thumbnailUrl: String = "",
    val uploaderName: String = "",
    val uploaderUrl: String = "",
    val duration: Long = 0L, // seconds
    val viewCount: Long = 0L,
    val uploadDate: String = "",
    val platform: Platform = Platform.UNKNOWN,
    val videoStreams: List<StreamFormat> = emptyList(),
    val audioStreams: List<StreamFormat> = emptyList(),
    val videoOnlyStreams: List<StreamFormat> = emptyList(),
    val subtitles: List<SubtitleTrack> = emptyList(),
    val isLive: Boolean = false,
    val sourceLayer: ExtractionLayer = ExtractionLayer.NEWPIPE,
    val originalUrl: String = ""
) {
    /**
     * Returns best available video+audio stream for quick download.
     * Prefers progressive streams (video+audio combined) for simplicity,
     * falls back to highest quality video-only + best audio for merging.
     */
    fun getBestStream(): StreamFormat? {
        // Prefer progressive (combined video+audio) streams
        return videoStreams.maxByOrNull { it.height }
            ?: videoOnlyStreams.maxByOrNull { it.height }
    }

    fun getBestAudioStream(): StreamFormat? {
        return audioStreams.maxByOrNull { it.bitrate }
    }

    /**
     * Groups all streams by quality tier for format selection UI.
     */
    fun getQualityTiers(): List<QualityTier> {
        val tiers = mutableListOf<QualityTier>()

        // Audio-only tier
        if (audioStreams.isNotEmpty()) {
            tiers.add(QualityTier("Audio Only", audioStreams.sortedByDescending { it.bitrate }))
        }

        // Video quality tiers
        val allVideoStreams = (videoStreams + videoOnlyStreams).distinctBy { "${it.height}p_${it.format}" }
        val grouped = allVideoStreams.groupBy {
            when {
                it.height >= 2160 -> "4K Ultra HD"
                it.height >= 1440 -> "1440p QHD"
                it.height >= 1080 -> "1080p Full HD"
                it.height >= 720 -> "720p HD"
                it.height >= 480 -> "480p SD"
                it.height >= 360 -> "360p"
                else -> "Low Quality"
            }
        }
        grouped.forEach { (label, streams) ->
            tiers.add(QualityTier(label, streams.sortedByDescending { it.bitrate }))
        }

        return tiers.sortedByDescending { it.streams.firstOrNull()?.height ?: 0 }
    }
}

data class QualityTier(
    val label: String,
    val streams: List<StreamFormat>
)

data class SubtitleTrack(
    val language: String,
    val languageCode: String,
    val url: String,
    val format: String = "vtt", // vtt, srt, ttml
    val autoGenerated: Boolean = false
)

enum class ExtractionLayer {
    NEWPIPE,
    YTDLP,
    INNERTUBE
}

enum class Platform(val displayName: String, val icon: String) {
    YOUTUBE("YouTube", "▶"),
    INSTAGRAM("Instagram", "📷"),
    TWITTER("Twitter/X", "🐦"),
    TIKTOK("TikTok", "🎵"),
    REDDIT("Reddit", "🔴"),
    FACEBOOK("Facebook", "👤"),
    DAILYMOTION("Dailymotion", "▶"),
    VIMEO("Vimeo", "🎬"),
    SOUNDCLOUD("SoundCloud", "🎧"),
    SNAPCHAT("Snapchat", "👻"),
    TORRENT("Torrent", "🧲"),
    UNKNOWN("Unknown", "🌐")
}
